# Generated by Django 2.0.2 on 2018-02-02 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test',
            new_name='Test1',
        ),
    ]
